backend/src/app.module.ts
frontend/package-lock.json
frontend/src/react-app-env.d.ts

- app.module 내 import에서 파일 이름 변경 적용
- frontend 내부 package-lock에 프로젝트 이름 적용

머지 후 오류 수정

---

backend/src/chatting.gateway.ts
frontend/src/components/Cam/ButtonBar.tsx
frontend/src/components/Cam/Cam.tsx
frontend/src/components/Cam/ChattingTab.tsx
frontend/src/components/Cam/MainScreen.tsx
frontend/src/components/Cam/UserListTab.tsx

- UserListTab은 드래그 가능한 Floating 요소로 만들 것이기 때문에 이를 기존 위치에서 분리하고 position:absolute 속성을 부여하였습니다.
- 이에 따른 MainScreen 및 ChattingTab 컴포넌트의 기본 크기를 변경하였습니다.
- ChattingTab에서 input 을 textarea 로 변경하였습니다.
+ 이제 여러 줄을 입력할 수 있고, 기본 width가 넘어가는 글자가 적히면 자동으로 개행이 됩니다.
+ textarea보다 글이 길어지면 일정 크기까지 늘어나다가 이후에는 스크롤이 출력합니다.
+ shift + enter를 누르면 메시지를 보내지 않고 개행하여 마저 작성할 수 있습니다.
- ChattingTab에서 메시지를 보낼 때의 데이터 타입 변경 및 메시지 출력 방식 또한 변경하였습니다.
+ 이제 메시지를 보낼 때 메시지를 보낸 현재 시간이 담긴 객체와 socket id를 함께 보냅니다.
+ 위 정보들을 사용하여 ChattingTab에서 메시지들을 보기 좋게 랜더링하도록 코드를 작성하였습니다.
- ChattingTab과 MainScreen 의 크기가 변화할 때 간단한 모션을 가지도록 css를 수정하였습니다.

UserListTab과 ChattingTab 컴포넌트 UI 및 일부 코드 변경 

---

frontend/src/components/Cam/Draggable.tsx
frontend/src/components/Cam/UserListTab.tsx
frontend/src/components/core/Draggable.tsx

- 자식컴포넌트를 draggable하게 만들어주기 위한 Draggable Component를 구현했습니다.
- UserListTab을 draggable하게 만들기 위해 Draggable Component로 감쌌습니다.

Draggable Component 구현

---

.github/workflows/cicd.yml

main과 dev에 PR이 있을 경우에 build와 test를 실행하도록 하였습니다.

PR시 github action 실행 되는지 확인

---

frontend/src/App.spec.tsx
frontend/src/components/Cam/ChattingTab.tsx
frontend/src/components/Cam/UserListTab.tsx
frontend/src/components/Cam/UserScreen.tsx
frontend/src/components/core/Draggable.tsx

- ChattingTab 의 메시지 입력 창 크기가 변하는 버그 수정
- UserListTab이 ChattingTab 아래로 가는 현상 수정
- UserListTab이 ChattingTab 위에서 움직일 때, 드래그가 정상적으로 동작하지 않는 버그 수정
- UserScreen의 video muted 빼기
- 해당 수정은 배포 후에도 동작하는지 확인해봐야 합니다.

UserListTab과 ChattingTab 관련 버그 수정

---

frontend/src/components/Cam/ButtonBar.tsx
frontend/src/components/Cam/Cam.tsx
frontend/src/components/Cam/MainScreen.tsx
frontend/src/components/Cam/SharedScreen.tsx

ButtonBar에 클릭 이벤트 핸들러를 상위 컴포넌트에서 받아서 연결하였습니다.
그리고 해당 이벤트 발생 시 Cam에서 화면 공유 상태와 공유하는 화면의 MediaStream을 상태로 갖습니다.
이를 하위 컴포넌트인 MainScreen에서 받아서 화면을 렌더링 하도록 구현하였습니다.

자신의 화면을 띄우는 기능

---

backend/src/cam/cam.controller.ts
frontend/src/components/Main/CamRooms.tsx

- api 를 호출할 때는 `api/xxx/xxx` 와 같은 형태로 호출하도록 변경
- `cam/create-room` , POST 를 `cam/room`, POST 로 변경
- `cam/is-room-exist` , POST 를 `cam/room`, GET 으로 변경

작성된 API 명을 Restful 하게 변경

---

backend/src/cam/cam.controller.ts
backend/src/cam/cam.gateway.ts
backend/src/cam/cam.service.ts
frontend/src/App.tsx
frontend/src/components/Cam/Cam.tsx
frontend/src/components/Main/CamRooms.tsx

- onSubmitJoinForm과 onSubmitCreateForm에서 중복된 부분을 분리하여 getUserInfoFromForm으로 만들었습니다.
- 방 목록으로 방에 접속하도록 수정
+ 새롭게 방을 만들거나, 이미 존재하는 방 목록을 통해 접속할 수 있도록 변경하였습니다.
- 지금 쓰이지 않는 LoginMain 대신 CamRooms 페이지를 메인 페이지로 설정하였습니다.
- CamRooms에서 nickname을 설정하지 않으면 접속할 수 없다는 알람을 띄우도록 하였습니다.

CamRooms 에서 방에 접속하는 방식 변경

---

frontend/src/components/Cam/SharedScreen/SharedScreenReceiver.ts
frontend/src/components/Cam/SharedScreen/SharedScreenSender.ts

PeerConnection이 close 되지 않는 버그가 존재해서 이를 수정하였습니다.

화면 공유 시 연결이 정리되지 않는 문제 수정

---

backend/src/app.module.ts
backend/src/comment/comment.entity.ts
backend/src/comment/comment.module.ts

comment entity에 user entity와의 관계를 설정하여 추가했습니다.

Comment 엔터티 설계

---

backend/src/channel/channel.entity.ts
backend/src/comment/comment.entity.ts
backend/src/emoticon/emoticon.entity.ts
backend/src/message/message.entity.ts

각 Entity별 연관관계 설정

---

backend/src/types/cam.ts
frontend/src/components/Cam/ChattingTab.tsx
frontend/src/components/Cam/STT/STTScreen.tsx
frontend/src/components/Cam/STT/STTStore.tsx
frontend/src/components/Cam/UserScreen.tsx
frontend/src/hooks/useSTT.ts
frontend/src/hooks/useUserMedia.ts
frontend/src/types/cam.ts

- STT에서 사용중인 SpeechRecognition 인스턴스를 재활용해서 말하고 있는 상태를 감지하는 기능을 구현하였습니다. 
- 본인을 제외한 다른 사람이 말을 하고 있으면 초록색 테두리로 하이라이트 됩니다.
- 기존에 장시간 말을 안하면 STT 객체가 종료되는 버그를 수정했습니다.
- speaking 상태를 추가하는 방식으로 구현했더니 깜빡임 현상이 심해서 또 해결법을 찾아야 할 것 같습니다.

다른 사람이 말하는 중이면 하이라이트 되는 기능 구현

---

backend/.eslintrc.js
backend/src/cam/cam.gateway.ts
backend/src/cam/cam.service.ts
backend/src/channel/channel.entity.ts
backend/src/comment/comment.entity.ts
backend/src/message/message.entity.ts
backend/src/user-server/user-server.controller.ts
backend/tsconfig.json

기존에 import를 하면 자동으로 src부터 시작되는 resolution을 가졌는데, 테스트 과정에서 오류가 발생했기 때문에 관련 tsconfig 설정을 수정하였습니다.

백엔드 tsconfig 수정

---

backend/src/channel/channel.controller.ts
backend/src/channel/channel.module.ts
backend/src/channel/channel.service.ts
backend/src/user-channel/user-channel.controller.ts
backend/src/user-channel/user-channel.entity.ts
backend/src/user-channel/user-channel.module.ts
backend/src/user-channel/user-channel.service.ts
backend/src/user/user.module.ts

tsconfig를 수정함에 따라 src/ 를 참고했던 경로를 모두 수정하였습니다.

src 관련 경로 수정

---

backend/src/server/server.controller.ts
backend/src/server/server.repository.ts
backend/src/server/server.service.spec.ts
backend/src/server/server.service.ts
backend/src/user-server/user-server.controller.ts
backend/src/user-server/user-server.service.spec.ts
backend/src/user-server/user-server.service.ts
frontend/src/components/Main/MainStore.tsx
frontend/src/components/Main/ServerListTab.tsx
frontend/src/components/Main/ServerModal/CreateServerModal.tsx
frontend/src/components/Main/ServerModal/JoinServerModal.tsx
frontend/src/components/Main/ServerModal/QuitServerModal.tsx
frontend/src/components/Main/ServerModal/ServerSettingModal.tsx

- 서버의 소유주를 확인하여 사용자와 일치하다면 서버를 삭제하는 기능을 구현하였습니다.
- 많은 컴포넌트에서 사용되는 getUserServerList함수를 store로 묶었습니다.

Server 삭제 기능 구현 및 연결

---

backend/src/comment/comment.controller.ts
backend/src/comment/comment.dto.ts
backend/src/comment/comment.entity.ts
backend/src/comment/comment.module.ts
backend/src/comment/comment.repository.ts
backend/src/comment/comment.service.ts
backend/src/message/message.service.ts
backend/src/user-server/user-server.service.ts

POST /api/commnets 
{
"channelId":number
"messageId": number,
"contents":string
}
GET /api/comments?messageId=?
형식으로 코멘트를 생성, 조회할 수 있습니다.

코멘트 생성, 조회 백엔드 

---

backend/src/server/server.controller.ts
backend/src/server/server.entity.ts
backend/src/server/server.service.spec.ts
backend/src/server/server.service.ts
backend/src/user-server/user-server.controller.ts
backend/src/user-server/user-server.service.spec.ts
backend/src/user-server/user-server.service.ts
frontend/src/components/Main/MainHeader.tsx
frontend/src/components/Main/ServerListTab.tsx
frontend/src/components/Main/ServerModal/CreateServerModal.tsx
frontend/src/components/Main/ServerModal/JoinServerModal.tsx
frontend/src/components/Main/ServerModal/ServerInfoModal.tsx
frontend/src/components/Main/ServerModal/ServerSettingModal.tsx
frontend/src/components/core/Dropdown.tsx

- Server 참가코드를 사용하여 서버에 참가하도록 변경하였습니다.
- Server 참가코드를 재생성할 수 있습니다.

Server 참가 코드 적용 

---

backend/src/message.gateway.ts
backend/src/message/message.controller.ts
backend/src/message/message.module.ts
backend/src/message/message.service.ts
backend/src/user-channel/user-channel.entity.ts
backend/src/user-channel/user-channel.service.ts
frontend/src/components/Main/ContentsSection/ContentsSection.tsx
frontend/src/components/Main/ContentsSection/MessageSection.tsx
frontend/src/components/Main/ContentsSection/ThreadSection.tsx
frontend/src/components/Main/MainSection.tsx
frontend/src/components/Main/MainStore.tsx
frontend/src/types/comment.ts
frontend/src/types/message.ts

- ThreadSection 코드를 작성하였습니다.
- Thread에서 Comment를 보내고 받을 수 있는 기능을 추가하였습니다.
- ThreadSection의 textarea를 통해 Comment를 보낼 수 있고, 해당 Message의 Comment들을 볼 수 있습니다.
- Socket 통신을 위하여 MessageSection에서 messageList 상태를 MainSection으로 끌어올렸습니다.
- Message를 전송하는 방식을 Socket으로 개선하였습니다.

ThreadSection 구현 & Message 전송에 Socket 통신 연결

---

frontend/src/components/LoginPage/LoginCallback.tsx
frontend/src/components/Main/Cam/CamListHeader.tsx
frontend/src/components/Main/ChannelListHeader.tsx
frontend/src/components/Main/ChannelModal/CreateChannelModal.tsx
frontend/src/components/Main/ChannelModal/JoinChannelModal.tsx
frontend/src/components/Main/MainSection.tsx
frontend/src/components/Main/ServerModal/CreateServerModal.tsx

- 채널 생성, 참가 시에 소켓에서도 참여하도록 합니다.
- 생성과 참가로 변경
- 서버 생성 모달에서 input 관련 버그 수정

배포전 몇몇 버그 수정

---

frontend/src/components/Main/ChannelModal/QuitChannelModal .tsx
frontend/src/components/Main/ChannelModal/UpdateChannelModal.tsx

모달 관련 상태 수정

---

backend/src/server/dto/response-server-users.dto.ts
backend/src/server/server.controller.ts
backend/src/server/server.entity.ts
backend/src/server/server.service.spec.ts
backend/src/server/server.service.ts
frontend/src/components/Main/MainHeader.tsx
frontend/src/components/Main/ServerModal/QuitServerModal.tsx
frontend/src/components/Main/ServerModal/ServerInfoModal.tsx
frontend/src/components/Main/ServerModal/ServerSettingModal.tsx
frontend/src/components/core/Dropdown.tsx
frontend/src/types/main.ts

- ServerSettingModal의 버튼 수를 줄였습니다.
- Server의 owner일 경우 드롭다운 메뉴로 서버설정, 서버정보를 띄웁니다.
- Server의 owner가 아닐 경우 드롭다운 메뉴로 서버정보, 서버나가기를 띄웁니다.

ServerSettingModal UI변경

---

backend/src/message.adapter.ts
backend/src/message.gateway.ts
frontend/src/components/Cam/CamStore.tsx
frontend/src/components/Main/ContentsSection/ContentsSection.tsx
frontend/src/components/Main/ContentsSection/ThreadSection.tsx
frontend/src/components/Main/MainSection.tsx
frontend/src/components/Main/MainStore.tsx
frontend/src/types/comment.ts

Thread 내부에 있던 CommentList를 socket event를 이용해서 관리하기 위해서 상위 컴포넌트인 MainSection으로 상태를 끌어올렸습니다. 그리고 socket에서 오는 이벤트를 받아 리스트에 추가하는 형태로 구현하였습니다.

Thread 부분 소켓 연결

---

backend/src/channel/channel.entity.ts
backend/src/server/server.controller.ts
backend/src/user-server/user-server.controller.ts
frontend/src/components/Main/MainPage.tsx
frontend/src/components/Main/MainSection.tsx
frontend/src/components/Main/MainStore.tsx
frontend/src/components/Main/ServerJoinSection.tsx
frontend/src/components/Main/ServerListTab.tsx
frontend/src/components/Main/ServerModal/QuitServerModal.tsx
frontend/src/components/Main/ServerModal/ServerDeleteCheckModal.tsx
frontend/src/components/Main/ServerModal/ServerSettingModal.tsx
frontend/src/types/fetch.ts
frontend/src/utils/fetchMethods.ts

- 참가한 Server가 없을 경우 참가코드를 입력하여 Server에 참가할 수 있는 창이 나타납니다.
- Server삭제시 확인 모달을 출력하도록 하였습니다.
- channel entity의 server에 cascade옵션을 추가하였습니다.

Server가 없을 경우의 화면 렌더링 구현 

---

backend/src/cam/cam-inner.service.ts
backend/src/cam/cam.gateway.ts
frontend/src/components/Cam/CamStore.tsx
frontend/src/components/Main/MainStore.tsx

- 툭하면 cam 인원이 가득 찼다고 나오는 버그 수정
- cam 관련 socket에 `/cam` namespace 적용
- 혹시 몰라서 socket이 unmount될때 cleaner 로직 구현

배포 후 cam socket 관련 오류 수정

---

backend/src/cam/cam.service.ts
frontend/src/components/Main/AlertModal.tsx
frontend/src/components/Main/Cam/List/CamListItem.tsx
frontend/src/components/Main/Cam/Modal/CamDeleteModal.tsx
frontend/src/components/Main/Cam/Modal/CreateCamModal.tsx
frontend/src/components/Main/Channel/List/ChannelListItem.tsx
frontend/src/components/Main/Channel/Modal/AlertDeleteChannel.tsx
frontend/src/components/Main/Channel/Modal/CreateChannelModal.tsx
frontend/src/components/Main/Channel/Modal/JoinChannelModal.tsx
frontend/src/components/Main/Channel/Modal/QuitChannelModal .tsx
frontend/src/components/Main/Channel/Modal/UpdateChannelModal.tsx
frontend/src/components/Main/ContentsSection/MessageSection.tsx
frontend/src/components/Main/ContentsSection/NoChannelSection.tsx
frontend/src/components/Main/Main.tsx
frontend/src/components/Main/MainPage.tsx
frontend/src/components/Main/MainStore.tsx
frontend/src/components/Main/Server/Modal/CreateServerModal.tsx
frontend/src/components/Main/Server/Modal/JoinServerModal.tsx
frontend/src/components/Main/Server/Modal/QuitServerModal.tsx
frontend/src/components/Main/Server/Modal/ServerDeleteCheckModal.tsx
frontend/src/components/Main/Server/Modal/ServerSettingModal.tsx
frontend/src/components/Main/ToggleStore.tsx
frontend/src/components/core/DropdownMenu.tsx
frontend/src/components/core/MainDropdown.tsx
frontend/src/components/core/MainModal.tsx

- MainStore 내부에 위치했던 modal, dropdown, alert 관련 상태를 ToggleStore로 분리해냈습니다.

MainStore 리팩토링

---

backend/src/cam/cam.controller.ts
backend/src/login/login.controller.ts
backend/src/user/user.controller.ts
frontend/src/App.tsx
frontend/src/atoms/user.ts
frontend/src/components/Cam/CamMain.tsx
frontend/src/components/Login/LoginCallback.tsx

- recoil selector를 이용해 매번 비동기적으로 로그인이 된 상태인지를 체크합니다.  
- 굳이 pr를 따로 판 이유는 여러분들이 꼭 자세히 봐주셨으면 해서 입니다ㅎㅎ 이제서야 진짜 recoil의 장점을 사용한 느낌이거든요
- recoil selector와 Suspense를 위주로 보시면 되겠습니다.

로그인 체크 로직 구현

---

backend/src/cam/cam.gateway.ts
backend/src/comment/comment.repository.ts
backend/src/message/message.repository.ts
frontend/src/components/Cam/CamStore.tsx
frontend/src/components/Cam/Menu/ButtonBar.tsx
frontend/src/components/Main/MainStore.tsx

socket 버그 수정
comment, message 정렬 로직 추가

socket 버그 수정, 정렬 로직 추가

---

backend/src/channel/channel.repository.ts

not joined channel list 수정

---

frontend/src/components/Main/MainSection.tsx

- 선택한 메시지가 존재하지 않을 수도 있어서 이를 확인합니다.

Fix : 코멘트를 받을 때 선택한 메시지가 존재하는지도 확인

---

backend/src/comment/comment.controller.ts

Fix : comment controller에서 query를 number로 파싱
